backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
site_url: "https://example.com"
media_folder: "src/static/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.njk"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/default.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "generic_pages"
    label: "Generic Pages"
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/default.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink Override (Pattern: '/your-slug/index.html')", name: "permalink", widget: "string", required: false}
      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
      - {label: "Social Image", name: "socialImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "Site Url", name: "url", widget: "string"}
          - {label: "Author Name", name: "authorName", widget: "string"}
          - {label: "Author Email Address", name: "authorEmail", widget: "string"}
          - {label: "Author Twitter Handle", name: "authorHandle", widget: "string", required: false}
          - {label: "Show Theme Credit", name: "showThemeCredit", widget: "boolean", default: true}
          - {label: "Favicon path (EG: /images/favicon.png)", name: "faviconPath", widget: "string"}
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Is url to external site?", name: "external", widget: "boolean", required: false}
